### ISSUE TITLE
author-can-merge: false does not seem to work

### ISSUE THREAD

**Issue by jrfnl** [srvaroa/labeler#123]
Hiya,

As one of the criteria in a `labeler.yml` file, I have the following:
``` yml
 labels:
   - label: "Status: triage"
     draft: false
     author-can-merge: false
```

### I'd expect

The `Status: triage` label to be added to all non-draft PRs where the author doesn't have commit rights in the repo.

### What actually happened

The `Status: triage` label does not get added to PRs from outside contributors (who don't have commit rights to the repo).

### Other info

I haven't tested yet if it works when I set it as follows, but if it does, I'd still find that counter-intuitive, as I'd expect `author-can-merge: false` to be respected.

```yml
labels:
  - label: "Status: triage"
    negate: true
    draft: false
    author-can-merge: true
```

**Comment by srvaroa** [comment]
Hi @jrfnl, what version are you using?

**Comment by srvaroa** [comment]
Nevermind, I just pushed a fix. I've added an extra test with the final condition you wanted to set.

**Comment by srvaroa** [comment]
Should be fixed in https://github.com/srvaroa/labeler/releases/tag/v1.8.1

Thanks for reporting. Let me know if this works as expected

**Comment by jrfnl** [comment]
Thank you for the quick response @srvaroa ! I am using `srvaroa/labeler@v1`, so the fix should come in automatically and as the repo I'm using it in is hyper-active at this moment (I'm taking over a big project in a fork, so people are porting their old PRs to the new repo), I should be able to let you know how things are going soon!

**Comment by srvaroa** [comment]
I will update v1 to point at v1.8.1 first thing tomorrow!

**Comment by srvaroa** [comment]
v1 is updated

**Comment by jrfnl** [comment]
@srvaroa I've been checking new PRs for a few days now and something still doesn't seem right.

The "triage" label now gets added to all PRs, even those of people who _can_ merge in the repo.

**Comment by srvaroa** [comment]
Hi @jrfnl i will take a look asap. Is this in a public repo where I can take a look at the logs?

**Comment by jrfnl** [comment]
@srvaroa Appreciated and yes, the repo is public. Sorry, I didn't add links before as, while the repo is public, the _news_ that the repo existed was not, but an announcement was made last week ;-)

Workflow file: https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/workflows/label-new-prs.yml
Config: https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/.github/labeler.yml
Logs: https://github.com/PHPCSStandards/PHP_CodeSniffer/actions/workflows/label-new-prs.yml

Here is one where the "triage" label now correctly got added for a contributor who doesn't have commit: https://github.com/PHPCSStandards/PHP_CodeSniffer/actions/runs/7144614939/job/19458612350
And here is one where the "triage" label incorrectly got added to one of my own PRs, while I do have commit: https://github.com/PHPCSStandards/PHP_CodeSniffer/actions/runs/7148232941/job/19468964257

**Comment by srvaroa** [comment]
@jrfnl it looks like the implementation of that condition was not considering all the roles that allow for committing to the base branch, only OWNER. 

This is released as v1.8.2, the v1 floating reference is also updated. Let me know if this makes things work as expected.

**Comment by jrfnl** [comment]
> @jrfnl it looks like the implementation of that condition was not considering all the roles that allow for committing to the base branch, only OWNER.

Interesting as I would have expected that repo to identify me as an owner too.
I'm the owner of the organisation + the admin of the repo, which effectively makes me the owner.

Could this be because this repo was originally a fork and was "decoupled" ?

> This is released as v1.8.2, the v1 floating reference is also updated. Let me know if this makes things work as expected.

Will do! Thanks @srvaroa for working on this!

**Comment by srvaroa** [comment]
I noticed in the logs you linked above that the action resolved the author as non-owner, so I suspected this was the problem. The fix is needed anyway, but do let me know if it doesn't evaluate as expected for your PRs and I'll look further into it.

Thanks for the bug reports!

**Comment by jrfnl** [comment]
> I noticed in the logs you linked above that the action resolved the author as non-owner, so I suspected this was the problem. The fix is needed anyway, but do let me know if it doesn't evaluate as expected for your PRs and I'll look further into it.
> 
> Thanks for the bug reports!

It may be a few days/week before I have enough info to evaluate fully.

There are basically three kind of PRs I'd like to see come in to be able to say for sure:
* One from me (should _not_ get "triage" label).
* One from a member in the organisation who has triage permission on the repo, but does not have commit (_should_ get "triage" label).
* One from an outside contributor to the repo (_should_ get "triage" label).

Will let you know how I get on.
